### ISSUE TITLE
Failed to query nomad-apm metric

### ISSUE THREAD

**Issue by diegombeltran** [hashicorp/nomad-autoscaler#254]
Trying to get percentage allocated cpu metric [as nomad-apm documentation](https://www.nomadproject.io/docs/autoscaling/plugins/apm#percentage-allocated) shows:

Changed apm name to default "nomad-apm" in case #216 still breaks functionality.

```
2020-09-02T10:54:02.399Z [INFO]  agent.worker.check_handler: querying source: check=cpu policy_id=bb541cbb-2ad1-ae91-e680-490200ab77fc source=nomad-apm strategy=target-value target=aws-asg query=percentage-allocated_cpu
2020-09-02T10:54:02.399Z [WARN]  agent.worker: failed to evaluate check: policy_id=bb541cbb-2ad1-ae91-e680-490200ab77fc target=aws-asg error="failed to query source: unsupported query type "percentage-allocated"" check=cpu
```

The config:
```
apm "nomad-apm" {
  driver = "nomad-apm"
}

[...]

check "cpu" {
    source = "nomad-apm"
    query  = "percentage-allocated_cpu"

    strategy "target-value" {
        target = 80
    }
 }
```

Am I doing something wrong?

**Comment by jrasell** [comment]
Hi @diegombeltran and thanks for raising this.

Within your `check "cpu"` block are you specifying a `target` block to indicate the target resource of the check? If not I believe this is causing the issue as the autoscaler internally uses the target block to extrapolate the query to differentiate between task group and node queries. Below is an example using the `aws-asg` target:

```
  target "aws-asg" {
    aws_asg_name        = "my-target-asg"
    node_class          = "high-memory"
    node_drain_deadline = "15m"
  }
``` 

If this is the problem I believe there are two areas we can help improve this:
- better documentation to help understand the requirements
- better logging when performing the APM query canonicalization

**Comment by diegombeltran** [comment]
Hello!

I think so:

```
policy {
  cooldown            = "2m"
  evaluation_interval = "1m"

  check "cpu" {
    source = "nomad-apm"
    query  = "percentage-allocated_cpu"

    strategy "target_value" {
        target = 80
    }
  }

  target "aws-asg" {
    dry-run             = "true"
    aws_asg_name        = "${traefik_asg}" <--not relevant
    node_drain_deadline = "5m"
  }
}
```

**Comment by jrasell** [comment]
@diegombeltran the `node_class` target parameter is required here as it allows the Nomad Autoscaler to group Nomad clients into logical pools of compute. This is the param as used by Nomad clients via the [node_class config option](https://www.nomadproject.io/docs/configuration/client#node_class). If your clients have this value empty; the Nomad Autoscaler when searching the list of Nomad nodes will assign all empty class nodes to the `"autoscaler-default-pool"` class.

There is a backlog item to allow discovery of nodes via config items such as the `aws_asg_name` but this work is currently unscheduled unfortunately.

I have also identified an error in the documentation [here](https://www.nomadproject.io/docs/autoscaling/plugins/target#class) that incorrectly details `class` rather than `node_class` as a required parameter.

**Comment by diegombeltran** [comment]
This works now as expected! Thank you very much!

**Comment by jrasell** [comment]
Great to hear @diegombeltran.

I have opened the following issue and PR to address items discovered during this discussion:
- https://github.com/hashicorp/nomad-autoscaler/issues/255
- https://github.com/hashicorp/nomad/pull/8813

I will close this issue out, please feel free to reopen if needed though.

**Comment by petrukngantuk** [comment]
>  If your clients have this value empty; the Nomad Autoscaler when searching the list of Nomad nodes will assign all empty class nodes to the "autoscaler-default-pool" class.

@jrasell so the `node_class` required to be configured in nomad client ? any workaround to avoid changing all nomad clients config ?
