### ISSUE TITLE
aws-asg plugin with assuming roles?

### ISSUE THREAD

**Issue by evandam** [hashicorp/nomad-autoscaler#526]
Hi folks,

I was just looking into hooking up the AWS ASG plugin and wondering if it's possible to assume a role without hooking up some custom solution for this, or if there's any recommended approach (besides Vault).

The example [here](https://www.nomadproject.io/docs/autoscaling/plugins/target/aws-asg) shows hard-coding credentials, but I'm assuming it's either this or falling back on the AWS SDK's credential provider chain?

**Comment by jrasell** [comment]
Hi @evandam, you're absolutely correct in your statement that the plugin will fall back to using the AWS SDK's credential provider.

I'll keep this issue open and mark it as a documentation improvement requirement. I feel we should make it explicit which authentication method you're able to use, rather than a single example as we currently have.

**Comment by lgfa29** [comment]
Hi @evandam 👋 

I believe this was resolved by https://github.com/hashicorp/nomad-autoscaler/pull/564, which is available in the `nightly` build and will be released soon.

Is this what you were looking for?

**Comment by evandam** [comment]
Hey @lgfa29 yeah this works, thanks for the update! I think I was hoping for an option to pass a role ARN and assume a role with STS but this should be fine too.
