### ISSUE TITLE
Sync with Terraform State

### ISSUE THREAD

**Issue by victorstewart** [hashicorp/nomad-autoscaler#605]
we use terraform, but also want to use nomad autoscaler to dynamically grow our infrastructure to meet both bursty and permanent resource volume changes.

we'd have to write a custom module for our cloud provider (Equinix Metal), but my concern is terraform being unaware of the nomad autoscaled infrastructure. 

is it possible to just alter my terraform variables and invoke terraform from the module to scales my machine count up/down?

when scaling down though, i assume the machine(s) need to be drained and task count lowered (but unsure in what order), before terraform being invoked?

and i assume it's possible to query specific data points from prometheus in the custom module we write, to logic on? 

would love some guidance on how to best achieve this.

**Comment by lgfa29** [comment]
Hi @victorstewart 👋 

I would not recommend mixing TF and the Autoscaler since you would end up with two potentially conflicting operations. If the goal is to handle different scaling patterns (bursty vs. scheduled for example) I would suggest you separate a set of clients that under the control of the Autoscaler and another set that you control via Terraform. 

In AWS this would be different Autoscaling Groups, but I don't know if there's anything equivalent to Equinix Metal.

As for draining the nodes before deleting via Terraform, yes, that would be ideal. You could use a [destroy-time provisioner](https://developer.hashicorp.com/terraform/language/resources/provisioners/syntax#destroy-time-provisioners) to call the Nomad API to trigger the drain, but that's outside the scope of the Autoscaler.

I'm going to close this as it doesn't seem there's anything we can do in the Autoscaler side, but feel free to reach out if you have any other questions 🙂
