### ISSUE TITLE
within_bounds_trigger logic

### ISSUE THREAD

**Issue by calh** [hashicorp/nomad-autoscaler#607]
Hello,

I have a concern with the implementation of the `within_bounds_trigger` logic [here](https://github.com/hashicorp/nomad-autoscaler/blob/main/plugins/builtin/strategy/threshold/plugin/plugin.go#L253-L266)

If a scaling policy is set for a minimum of 2, maximum of 20 for example, then the default setting of 5 for this value will never trigger a scaling operation.  The logs will show something like "found 2 data points within bounds... not enough data points within bounds"

If the `within_bounds_trigger` is set low like 1 or 2 and the container count is high, like 15, then small deviations in load balancing can falsely trigger a scaling event.

I think a better algorithm for the `withinBounds` function is to apply some kind of aggregation across all of the containers.  Either average or median, or maybe even pull the same stats function used in the check query, if it's possible.  Or, maybe an even easier solution is to set the `within_bounds_trigger` integer to be dynamic based on a percentage of the running container count.  So for example, "trigger if 50% of the containers fall within the threshold bounds of the strategy"

Thanks for considering this!

A quick snippet of my config during testing:

```
    scaling { 
      enabled = true
      min = 2 
      max = 20
      policy {
        evaluation_interval = "40s"
        cooldown = "10m"
        
        check "high cpu utilization" {
          source = "nomad-apm"
          query  = "avg_cpu-allocated"
          query_window = "5m" 
          group = "cpu-allocated"
          strategy "threshold" { 
            lower_bound = 70
            delta = 4
            within_bounds_trigger = 1
          }
        }
        check "low cpu utilization" {
          source = "nomad-apm"
          query  = "avg_cpu-allocated"
          group = "cpu-allocated"
          strategy "threshold" {
            upper_bound = 30 
            delta = -1 
            within_bounds_trigger = 1
          } 
        } 
      } 
    } 
```

**Comment by calh** [comment]
As a follow-up thought to this, perhaps providing a job count as a variable would be helpful in a few situations.

For example, let's say that the job is deployed with a `job->group->count = 2` and the same scaling policy as above.  If the tasks are running hot and have 15 allocations, a deployment will reset the container count to 2 and starve the application of capacity until the autoscaler kicks in and scales it back up again.

Since `$NOMAD_ALLOC_INDEX` is available as an environment variable, I'm guessing that it would be a relatively light level of effort to add something like `$NOMAD_ALLOC_COUNT` to represent the number of allocations currently running in this task group.  Then using some arithmetic expressions and boolean defaults:

```
job "myjob" {
  group "mygroup" {
    # Keep the count the same unless this is the first deployment
    count = "${NOMAD_ALLOC_COUNT}" || 2
    task "mytask" { ... }
    scaling {
      min = 2
      max = 20
      policy {
        check "high cpu" {
          source = "nomad-apm"
          query  = "avg_cpu-allocated"
          strategy "threshold" {
            lower_bound = 70
            delta = 4
            # if 50% of our allocations are over 70% utilization
            within_bounds_trigger = "${NOMAD_ALLOC_COUNT}" * 0.50
        }
      }
    }
  }
}
```

**Comment by lgfa29** [comment]
Hi @calh 👋 

Thank you for the thoughtful suggestion, and apologies for the delay on getting to this issue.

I think there may be some misunderstanding here, either from my side not understanding your proposal, or from your side about what `within_bounds_trigger` is counting 😅 

So let me try to explain how the threshold plugin works so we can try to clear things out.

Using your first policy as example, we have two checks that use the threshold strategy (I removed `delta` since it's not relevant in this case):

```hcl
strategy "threshold" { 
  lower_bound = 70
  within_bounds_trigger = 1
}

strategy "threshold" {
  upper_bound = 30 
  within_bounds_trigger = 1
} 
```

The autoscaler will query your APM from time to time (`40s` in the example) to retrieve a time window of metrics. That would look something like this:
![image](https://github.com/hashicorp/nomad-autoscaler/assets/775380/f5c051c2-c45a-4cdd-885d-8bcb35121d04)

From the strategy perspective, it doesn't really matter where these data points are coming from, that's up to your APM query. You could take an average over all containers, some kind of median or mean, whatever fits your needs best (side node, the `nomad-apm` in the example is not powerful enough to provide this type of flexibilty, so in cases like this it's best to use a proper APM system).

The only thing it cares about is determine if these metrics can be considered relevant enough to trigger a scaling action.

On `Time Window 1` it's pretty obvious that the answer is **no**, we don't have any data point inside any of the boundaries set by the thresholds, so neither check is activated.

`Time Window 2` is a little more questionable because we do have one data point within the upper threshold boundary, but then most of the other metric values fall outside. Is that relevant enough to say the `high cpu utilization` check should be triggered? 

Now `Time Window 3` is a little more clear, most of the data points fall within its bounds, so it's probably fair to claim that `low cpu utilization` **should** be triggered.

And that's what `within_bounds_trigger` is counting: how many data points need to fall within bounds to consider the check triggered.

There's not really a good answer, so each user will need to adjust to their needs. The main goal here is to prevent unnecessary scaling actions due to a spike or an outlier.

Perhaps more dynamics values as you mentioned could be useful, like `within_bounds_trigger = "50%"`, or maybe we could assign a weight to each data point so that most recent values are more relevant than old ones.

But the key thing to note here is that this configuration is counting **data points** not containers or servers.

Does this make sense?

**Comment by calh** [comment]
Thank you for the description @lgfa29, you can close this issue.

**Comment by lgfa29** [comment]
Awesome, glad it helped clear things out 😄 

Feel free to reach out if you have any more questions.
