### ISSUE TITLE
Threshold Strategy: lower_bound behavior does not match docs

### ISSUE THREAD

**Issue by jaltavilla** [hashicorp/nomad-autoscaler#727]
The docs state that when lower_bound is specified and upper_bound omitted, that the lower bound is non-inclusive. However, this is not the case. The comparison is always inclusive (`>=`).  The specific piece of documentation I'm referencing can be found at the end of [https://developer.hashicorp.com/nomad/tools/autoscaling/plugins/strategy/threshold](https://developer.hashicorp.com/nomad/tools/autoscaling/plugins/strategy/threshold).
> Similarly, if upper_bound is not defined, any value above lower_bound will be considered within bounds.

We discovered this discrepancy when the below policy resulted in the asg scaling up to its max.

``` 
        # If nomad indicates that the cluster is missing cpu to schedule an allocation, then we need to add an ec2 instance
        check "missing-cpu" {
            source          = "datadog"
            query           = "default_zero(sum:nomad.nomad.blocked_evals.cpu{ {{template "byRoleTags" .asg.role}} }.rollup(sum).weighted())"
            query_window    = "3m"
            group           = "blocked-cpu"
            strategy "threshold" {
                lower_bound = 0
                delta       = 1
            }
        }
```

The relevant code can be found at https://github.com/hashicorp/nomad-autoscaler/blob/3a7e8c2ef1189c68b992060716bedf24cd2da25f/plugins/builtin/strategy/threshold/plugin/plugin.go#L262. The comparison doesn't change if there is no upper bound specified. Nor does `parseBound` above alter the lower bound with something like math.Nextafter (which is probably a bad idea anyway).

Semi-related, I wonder if `parseBound` should be using `math.Inf` instead of `math.MaxFloat64`. If a metric ever returned a max float64 it would never be within the bounds of a threshold, even one that was a lower bound only. It seems unlikely, but some poor engineer would have a very confusing experience. 😆

**Comment by lgfa29** [comment]
Hi @jaltavilla 👋 

Nice catch! The docs and the code are actually quite vague on the expected behaviour here...

Reading the original issue (https://github.com/hashicorp/nomad-autoscaler/issues/438) it seems like `lower_bound` always being inclusive and `upper_bound` always being exclusive (as it's currently coded) was the original design, but I can't really remember why 😅 

I think the idea was to avoid confusion if you have multiple tiers. In the example provided, a value of exactly `70` would fall into `scale_out_high_threshold_zone` and not `scale_out_low_threshold_zone`.

If we special case the scenario where `lower_bound` changes behaviour then the exact `70` wouldn't actually fall anywhere (and if both values were inclusive then it would fall into both).

So I think the documentation needs to be update to be more clear about it. Apologies for the problems the lack of clarity here caused.

I've opened https://github.com/hashicorp/nomad/pull/19552 to update the docs and https://github.com/hashicorp/nomad-autoscaler/pull/815 to add some test cases and use `math.Inf`, thanks for the tip!

**Comment by jaltavilla** [comment]
Thanks for taking a look at this! Having the bounds checks remain consistent regardless of which are present makes a lot of sense. The checks changing as an upper was added/removed would likely be surprising 😆
